name: GitHub Actions Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    environment:
      name: Preview
      url: ${{ steps.trigger_vercel.outputs.vercel-deploy }}
    steps:
      - uses: actions/checkout@v3

      - name: install dependencies
        run: |
          npm ci
      - name: Check types
        run: |
          npm run type-check

      - name: Install Vercel CLI
        run: npm install --global vercel@canary

      - name: Pull Vercel Environment Information
        run:
          vercel pull --yes --environment=preview --token=${{
          secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel (as background job)
        run: |
            echo bash -c "vercel deploy --token=${{ secrets.VERCEL_TOKEN }} &"
        id: trigger_vercel

      - name: Extract Preview URL
        run: |
            output="$GITHUB_OUTPUT"  

            preview_url=$(grep -Eo "Preview: https.*" <<< "$output")

            preview_url=${preview_url##*:}

            echo "Preview URL: $preview_url"

      - name: Display logs
        run: |
          echo ${{steps.trigger_vercel.outputs.vercel-deploy}}


      # - uses: actions/github-script@v3
      #   with:
      #     github-token: ${{secrets.GITHUB_TOKEN}}
      #     script: |
      #       github.issues.createComment({
      #         issue_number: context.issue.number,
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         body: 'The preview URL is: VERCEL PREVIEW URL.'
      #       });

        # run: |
        #    echo "vercel-deploy=$(bash -c "vercel deploy --token=${{ secrets.VERCEL_TOKEN }} &")" >> $GITHUB_OUTPUT