name: GitHub Actions Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    environment:
      name: Preview
      # url: ${{ steps.trigger_vercel.outputs.vercel-deploy }}
      url: https://full-stack-dev-q0bbnixpi-szemil.vercel.app
    steps:
      - uses: actions/checkout@v3

      - name: install dependencies
        run: |
          npm ci
      - name: Check types
        run: |
          npm run type-check

      - name: Install Vercel CLI
        run: npm install --global vercel@canary

      - name: Pull Vercel Environment Information
        run:
          vercel pull --yes --environment=preview --token=${{
          secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel (as background job)
        run: |
            url="$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})"
            vercel alias --token=${{ secrets.VERCEL_TOKEN }} set "$url" full-stack-dev-q0bbnixpi-szemil.vercel.app
        id: trigger_vercel


      - name: Display logs
        run: |
          echo ${{steps.trigger_vercel.outputs.vercel-deploy}}

#https://full-stack-dev-q0aanixpi-szemil.vercel.app
      # - uses: actions/github-script@v3
      #   with:
      #     github-token: ${{secrets.GITHUB_TOKEN}}
      #     script: |
      #       github.issues.createComment({
      #         issue_number: context.issue.number,
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         body: 'The preview URL is: VERCEL PREVIEW URL.'
      #       });

      # bash -c "vercel deploy --token=${{ secrets.VERCEL_TOKEN }} &"

        # run: |
        #    echo "vercel-deploy=$(bash -c "vercel deploy --token=${{ secrets.VERCEL_TOKEN }} &")" >> $GITHUB_OUTPUT