name: GitHub Actions Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    environment:
      name: Preview
      url: ${{ steps.trigger_vercel.outputs.vercel-deploy-url }}

    steps:
      - uses: actions/checkout@v3

      - name: install dependencies
        run: |
          npm ci
      - name: Check types
        run: |
          npm run type-check

      - name: Install Vercel CLI
        run: npm install --global vercel@canary

      - name: Pull Vercel Environment Information
        run:
          vercel pull --yes --environment=preview --token=${{
          secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel (as background job)
        run: |
          timeout 10 bash -c "vercel deploy --token=${{ secrets.VERCEL_TOKEN }} 2>&1 > deploy.log &"

      - name: Show Deploy Log
        id: vercel-url
        run: |

          vercel_deploy_url=$(grep -Eo "https?://[^ ]+" deploy.log)
      
          echo "vercel-deploy-url=$vercel_deploy_url"
      
          echo "vercel-deploy-url=$(grep -Eo "https?://[^ ]+" deploy.log)" >> $GITHUB_OUTPUT
      - name: Display URL
        run: |
          echo ${{steps.vercel-url.outputs.vercel-deploy-url}}

  # echo "vercel-deploy=$(bash -c "vercel deploy --token=${{ secrets.VERCEL_TOKEN }} &")" >> $GITHUB_OUTPUT

#https://full-stack-dev-q0aanixpi-szemil.vercel.app
# - uses: actions/github-script@v3
#   with:
#     github-token: ${{secrets.GITHUB_TOKEN}}
#     script: |
#       github.issues.createComment({
#         issue_number: context.issue.number,
#         owner: context.repo.owner,
#         repo: context.repo.repo,
#         body: 'The preview URL is: VERCEL PREVIEW URL.'
#       });

# bash -c "vercel deploy --token=${{ secrets.VERCEL_TOKEN }} &"
