name: GitHub Actions Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    environment:
      name: Production
      url: ${{ steps.vercel-url.outputs.vercel-deploy-url }}

    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: |
          npm ci
      - name: Check types
        run: |
          npm run type-check

      - name: Install Vercel CLI
        run: npm install --global vercel@canary

      - name: Pull Vercel Environment Information
        run:
          vercel pull --yes --environment=preview --token=${{
          secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel (as background job)
        run: |
           bash -c "vercel deploy --no-wait --prod --token=${{ secrets.VERCEL_TOKEN }} >deploy.log"

      - name: Show Deploy Log
        id: vercel-url
        run: |     
          echo "vercel-deploy-url=$(cat deploy.log)" >> $GITHUB_OUTPUT
